matrix:
  include:
    - os: linux
      language: python
      dist: trusty
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-czechslovak texlive-generic-extra lmodern latexmk latex-xcolor
      install:
        - pip install pygments
      script:
        - make pdfs
    - os: osx
      language: objective-c
      osx_image: xcode9
      install:
        - brew install marathon-swift
      script:
        - (cd backpack-problem; make test)
        - (cd three-sat; make release)
deploy:
  provider: releases
  api_key:
    secure: fhOIHXg+5cIVerKuADY10+ir9lulydUUEkgj25sklWQsqwB+l8U1iwMSMZDZtaM07c5DLof1OZpCjWPH8SaVAVHd/xmhHea9Fho0oIWPUKTMKDMstn2zenTxjRtRcz+BKRJ5V3Om4GQzOha+6hAa3vwQy+ma+aTpwuqKnfSbKkZVRVRz2lDqQ0nXWr9KWnwdIJorEjQ9iBPg3kN4ydY33wFzTTyDyTzi/K55YRN5Cqn00HjpZ+JkVeS2mb/zU79KmuMgRLiF32+L3pJKWHe920P6JBZSP0mglJtjnF28gZQ4LcNpQIePFEJL7ySgNL9m8V/pYLkq75y6BdLGdDdrSy5F6GxhqetJ73T1BC3rUxSLKZJwpF7E4g/h634P2eKeMSO8TaWogA311s0st6rpoSltW0dYXCKUymBPzgQlgCbJ190osZY1SPyVKWb6iDD6JmhR877FllifKJ5EhtzStNN8UzyNfLoA9BF5mykQPTOjcX0DIp9YJuZIe8DyNGSHBnN8ARX2wUGqk65nP6XAqlptUZC2rCbw2dDLrDoy+zMEy1gquBzB6PWV6AGG8zBG9clsxldLbrNFcPEJzwfPbyohtuX1owry+GOJ9h0UqpeTODJ72Ye6tM0xhVBd0zhhYx7kZdvIsuo2lICe/jq3P7tQ7jAsWhPqrZBRtd0QXmo=
  file_glob: true
  file: "*.pdf"
  skip_cleanup: true
  on:
    repo: josefdolezal/fit-mi-paa
    tags: true  
    condition: $TRAVIS_OS_NAME = linux
